language: ruby
cache: bundler
rvm:
- 2.1.2
before_install:
- gem install bundler --pre
before_script:
- bundle exec rake test_app
- cd spec/dummy
- sed -i $'7i\\\n \*\= require spree\/frontend\n' vendor/assets/stylesheets/spree/frontend/all.css
- sed -i $'7i\\\n \*\= require spree\/backend\n' vendor/assets/stylesheets/spree/backend/all.css
- sed -i $'10i\\\n\/\/\= require spree\/frontend\n' vendor/assets/javascripts/spree/frontend/all.js
- sed -i $'10i\\\n\/\/\= require spree\/backend\n' vendor/assets/javascripts/spree/backend/all.js
- cd ../..
script: DISPLAY=:99.0 bundle exec rspec spec
notifications:
  email:
    recipients:
    - none@example.com
    on_failure: change
    on_success: never
env:
  matrix:
    secure: Bpe13wRbj4RrfqrROu6HHWL58DpRlumZqUm22gMK1RHomkuZ5W5sc9Q6MEITt+MihbagmhmbNu7vztU+xdr1m+OlNaibvJeWKZEOyvvRKodUofCBBG677khzsJ2VxQeaboE7BfsPxIL0XaEkGQiVSU0lfdMi62D04Xbb6SxIWoA=
