language: ruby
cache: bundler
rvm:
- 2.1.2
before_install:
- gem install bundler --pre
before_script:
- bundle exec rake test_app
script: DISPLAY=:99.0 bundle exec rspec spec
notifications:
  email:
    recipients:
    - none@example.com
    on_failure: change
    on_success: never
env:
  global:
    secure: rK79pr+jpARJRPG79WD76v1GMWUm6XnTMr4dUWJk6QgFHB1AMYc3UURccWvlPmVKG3iSJ1rd4SWoajNosYXbL1CMP6LvNNCIeOa+QoLxBu2npXP5fUIt7HmD4b17mcT9sShjU8YValwbHGhfUnEmpP5AGjQSF21dsDDOANWlRKA=
