language: ruby
cache: bundler

rvm:
  - 2.1.2

before_install: 
  - "gem install bundler --pre"

#install:

before_script:
  - "bundle exec rake test_app"
  - "sed -i $'7i\\\n \*\= require spree\/frontend\n' vendor/assets/stylesheets/spree/frontend/all.css"
  - "sed -i $'7i\\\n \*\= require spree\/backend\n' vendor/assets/stylesheets/spree/backend/all.css"
  - "sed -i $'10i\\\n\/\/\= require spree\/frontend\n' vendor/assets/javascripts/spree/frontend/all.js"
  - "sed -i $'10i\\\n\/\/\= require spree\/backend\n' vendor/assets/javascripts/spree/backend/all.js"

script: "DISPLAY=:99.0 bundle exec rspec spec"
#script: 'bundle exec rake'

# after_script:

notifications:
  email:
    recipients:
      - none@example.com
    on_failure: change
    on_success: never